name: Prod build-deploy

on: [workflow_dispatch]

jobs:
  production:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: production
    permissions:
      contents: read
      packages: write
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - run: env
      - run: set
      - run: hostname
      - run: echo QUIT | nc localhost 6379
      - run: echo QUIT | nc $HOSTNAME 6379

      - name: Login to GitHub Container Registry
        id: docker-login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install werf
        id: install-werf
        uses: werf/actions/install@v1.2
        with:
          channel: stable
          version: v1.2.227

      - uses: actions/checkout@v3
        id: checkout
        with:
          fetch-depth: 0

      #- uses: thaind0/envfile@v1
        #with:
          #secrets: ${{ toJSON(secrets) }}
          #file: env.secrets


      - uses: werf/actions/converge@v1.2
        id: werf
        with:
          channel: stable
          version: v1.2.227